# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d22f5ceaf3cbbb6af2b1c945e5800930c09d9cd678a12fda9f9add1bc99e312921603366c1447b3af2473f4815a1a990f519f6e10122bccc0e6b02b7c1fa9d2

test:
  secret_key_base: 63b35b696afa9d3b95a93e1171c4f863314d4f015b2567037f129f73ae6ae5e09c53c22422ddca5903e96b854f4b01d790804ddf088fc0467fd27ca5ba9d83f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
